from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, runtime_checkable

from lxml import etree as ET

from models.row_data import RowData


@runtime_checkable
class ICache(Protocol):
    def get_rows(self, path: str) -> list[RowData] | None: ...
    def set_rows(self, path: str, rows: list[RowData]) -> None: ...
    def get_tree(self, path: str) -> ET.ElementTree | None: ...
    def set_tree(self, path: str, tree: ET.ElementTree) -> None: ...
    def invalidate(self, path: str) -> None: ...
    def clear_all(self) -> None: ...


@runtime_checkable
class IXmlRepository(Protocol):
    def parse_file(self, path: str) -> list[RowData]: ...
    async def parse_file_async(self, path: str) -> list[RowData]: ...
    def save(self, path: str, rows: list[RowData]) -> None: ...
    async def save_async(self, path: str, rows: list[RowData]) -> None: ...
    def invalidate_cache(self, path: str) -> None: ...


@runtime_checkable
class IConfigService(Protocol):
    def load_files(self, ce_path: str) -> list[str]: ...
    def get_ce_element(self, ce_path: str) -> ET.Element | None: ...
    def get_ce_folder(self, ce_path: str) -> str | None: ...
    def get_types_dir(self, ce_path: str) -> str | None: ...
    def create_type_file(self, ce_path: str, filename: str) -> str | None: ...
    def delete_type_file(self, ce_path: str, filename: str) -> bool: ...
    def add_file_to_ce(self, tree: ET.ElementTree, filename: str) -> bool: ...
    def remove_file_from_ce(self, tree: ET.ElementTree, filename: str) -> bool: ...


@runtime_checkable
class ISettingsService(Protocol):
    async def load_settings(self) -> dict[str, object]: ...
    async def save_setting(self, key: str, value: object) -> None: ...


@runtime_checkable
class IUpdateService(Protocol):
    async def check_for_updates(
        self, current_version: str, show_up_to_date: bool = False
    ) -> None: ...


@runtime_checkable
class IProjectService(Protocol):
    def load_projects(self) -> list[object]: ...
    def add_project(self, project: object) -> None: ...
    def remove_project(self, name: str) -> None: ...
    def get_project(self, name: str) -> object | None: ...
    def mark_opened(self, project: object) -> None: ...
    def get_last_project(self) -> object | None: ...


@runtime_checkable
class IEconomyService(Protocol):
    def find_config(self, economy_dir: str) -> str | None: ...
    def get_type_files(self, economy_dir: str) -> dict[str, str]: ...
    def get_types_dir(self, economy_dir: str) -> str: ...
    def get_known_files(self, directory: str) -> dict[str, str]: ...
    def get_all_editable_files(self, economy_dir: str) -> dict[str, str]: ...


@runtime_checkable
class IDetailPanel(Protocol):
    def show(
        self, row: RowData, usage_options: list[str], value_options: list[str]
    ) -> None: ...
    def hide(self) -> None: ...
    def refresh(self) -> None: ...
    def build(self) -> object: ...


@runtime_checkable
class IBatchPanel(Protocol):
    def show(
        self,
        header_text: str,
        usage_options: list[str],
        value_options: list[str],
        flag_names: list[str],
    ) -> None: ...
    def hide(self) -> None: ...
    def build(self) -> object: ...
    def get_values(self) -> dict[str, object]: ...


@runtime_checkable
class IChipSet(Protocol):
    def add(self, value: str) -> None: ...
    def remove(self, value: str) -> None: ...
    def get_values(self) -> list[str]: ...
    def build_controls(self) -> object: ...
    def refresh(self) -> None: ...


@runtime_checkable
class IEconomyEditor(Protocol):
    def load_project(self, project: object) -> None: ...
    def unload(self) -> None: ...


@runtime_checkable
class IDirtyState(Protocol):
    @property
    def is_dirty(self) -> bool: ...
    def mark_dirty(self) -> None: ...
    def mark_clean(self) -> None: ...
    def reset(self) -> None: ...


@runtime_checkable
class IPagination(Protocol):
    @property
    def page_index(self) -> int: ...
    @page_index.setter
    def page_index(self, value: int) -> None: ...
    @property
    def page_size(self) -> int: ...
    def total_pages(self, total_items: int) -> int: ...
    def visible_range(self, total_items: int) -> tuple[int, int]: ...


@runtime_checkable
class ISearch(Protocol):
    @property
    def query(self) -> str: ...
    @property
    def case_sensitive(self) -> bool: ...
    def filter_rows(self, rows: list[RowData]) -> list[int]: ...


@runtime_checkable
class IRemoteConnection(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def list_files(self, path: str) -> list[str]: ...
    async def download_file(self, remote_path: str, local_path: str) -> None: ...
    async def upload_file(self, local_path: str, remote_path: str) -> None: ...
    @property
    def connected(self) -> bool: ...


@runtime_checkable
class ITableController(Protocol):
    def render(
        self,
        rows: list[RowData],
        filtered: list[int],
        page_idx: int,
    ) -> None: ...
    def sync_back(
        self,
        rows: list[RowData],
        filtered: list[int],
        page_idx: int,
    ) -> None: ...
    def clear(self) -> None: ...
